name = "Chris Miller"
icon = "icon.jpg"
pronouns = "he/they"
interests = "Kubernetes, Game Dev, Rust, Coffee"
description = "Chris is a SWE at Microsoft attempting to push the Rust agenda. Outside of his day job, they can be found tinkering on home labs, trying to make games, or at their local coffee shop."

[[websites]]
name = "Github"
link = "https://github.com/ChristopherJMiller"

[[websites]]
name = "Website"
link = "https://chrismiller.xyz"
